### ISSUE TITLE
Installing Veil in Kali 2017.3

### ISSUE THREAD

**Issue by z0mb1es** [Veil-Framework/Veil#203] opened 2018-04-29 12:32 UTC
## Veil version
 Veil 3.0

## OS Used - all info (architecture, linux flavor, etc)
Kali Linux 2017.3 x86_64

## How did you install Veil? (Apt, Clone from Github, etc.)
git clone 

## Did you run the setup script?
Yup

## Pastebin link to error you are encountering (include console actions you took prior to error)
![captura de pantalla de 2018-04-29 09-14-17](https://user-images.githubusercontent.com/38834272/39406495-ea63f972-4b8d-11e8-8a7d-edf24180c079.png)

## Expected behavior
Well, install Veil; but I get this Python 3.4.4 Windows installation. 

## Any additional info you want to tell me
It's not the first time this happens. I've tried to install Veil on a VM and in a LiveCD. Now, I installed kali and deleted windows. but It still doesn't work.

**Comment by g0tmi1k** [comment] 2018-04-29 14:31
This is by design =)

Like it says in the terminal behind it: `Installing (Wine) python`
Its running A windows binary, python setup.
It also tells you todo: "next -> next -> next".

If you don't want todo anything, it all be automated, add `--silent` 
So: `bash config/setup.sh --silent`

...and you may wish todo it on Kali 2018.1 as that is supported

**Comment by ChrisTruncer** [comment] 2018-05-08 02:51
closing this issue - please open a new issue if you are encountering any problem.

**Closed as completed by ChrisTruncer** 2018-05-08 02:51 UTC
